### PR TITLE
Pass kwargs to Faker

### PR DESCRIPTION
**Pull request by prescod**
Fix regression where function arguments were not passed to faker properly.

### CODE REVIEW

**Review by davisagli — COMMENTED** [review]
Does faker ever use positional args?

**Comment by prescod** [comment]
Faker does not seem to require positional args and all example code uses keyword-arg syntax. I'm comfortable with enforcing that in Snowfakery.

**Comment by davisagli** [comment]
@prescod My question is more whether there are existing recipes that call faker with positional args, which we would break.

**Comment by prescod** [comment]
It's possible that someone discovered that syntax by themselves, but I haven't seen it. The would have had their code broken 2 weeks ago but they might not have upgraded. I can put a note in the release notes.

**Review by davisagli — APPROVED** [review]

**Pull request merged**
